<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Contoso University</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="demo.asp">Home</a></li>
      <li><a href="about.asp">About</a></li>
      <li><a href="student.asp">Student</a></li>
      <li><a href="course.asp">Course</a></li>
      <li><a href="enrollment.asp">Enrollment</a></li>
    </ul>
  </div>
</nav>